vrobbler/apps/beers/urls.py
from django.urls import path
from beers import views

app_name = "beers"


urlpatterns = [
    path("beers/", views.BeerListView.as_view(), name="beer_list"),
    path(
        "beers/<slug:slug>/",
        views.BeerDetailView.as_view(),
        name="beer_detail",
    ),
]

vrobbler/apps/books/urls.py
from django.urls import path
from books import views

app_name = "books"


urlpatterns = [
    path("books/", views.BookListView.as_view(), name="book_list"),
    path(
        "books/<slug:slug>/",
        views.BookDetailView.as_view(),
        name="book_detail",
    ),
    path(
        "authors/<slug:slug>/",
        views.AuthorDetailView.as_view(),
        name="author_detail",
    ),
]

vrobbler/apps/foods/urls.py
from django.urls import path
from foods import views

app_name = "foods"


urlpatterns = [
    path("foods/", views.FoodListView.as_view(), name="food_list"),
    path(
        "foods/<slug:slug>/",
        views.FoodDetailView.as_view(),
        name="food_detail",
    ),
]

vrobbler/apps/scrobbles/urls.py
from django.urls import path
from scrobbles import views
from tasks.webhooks import todoist_webhook

app_name = "scrobbles"

urlpatterns = [
    path("status/", views.ScrobbleStatusView.as_view(), name="status"),
    path(
        "manual/lookup/",
        views.ManualScrobbleView.as_view(),
        name="lookup-manual-scrobble",
    ),
    path(
        "long-play-finish/<slug:uuid>/",
        views.scrobble_longplay_finish,
        name="longplay-finish",
    ),
    path(
        "upload/audioscrobbler/",
        views.AudioScrobblerImportCreateView.as_view(),
        name="audioscrobbler-file-upload",
    ),
    path(
        "upload/koreader/",
        views.KoReaderImportCreateView.as_view(),
        name="koreader-file-upload",
    ),
    path(
        "lastfm-import/",
        views.lastfm_import,
        name="lastfm-import",
    ),
    path(
        "webhook/web-scrobbler/",
        views.web_scrobbler_webhook,
        name="web-scrobbler-webhook",
    ),
    path(
        "webhook/gps/",
        views.gps_webhook,
        name="gps-webhook",
    ),
    path(
        "webhook/jellyfin/",
        views.jellyfin_webhook,
        name="jellyfin-webhook",
    ),
    path(
        "webhook/mopidy/",
        views.mopidy_webhook,
        name="mopidy-webhook",
    ),
    path("webhook/todoist/", todoist_webhook, name="todoist-webhook"),
    path("export/", views.export, name="export"),
    path(
        "imports/",
        views.ScrobbleImportListView.as_view(),
        name="import-detail",
    ),
    path(
        "imports/tsv/<slug:slug>/",
        views.ScrobbleTSVImportDetailView.as_view(),
        name="tsv-import-detail",
    ),
    path(
        "imports/lastfm/<slug:slug>/",
        views.ScrobbleLastFMImportDetailView.as_view(),
        name="lastfm-import-detail",
    ),
    path(
        "imports/koreader/<slug:slug>/",
        views.ScrobbleKoReaderImportDetailView.as_view(),
        name="koreader-import-detail",
    ),
    path(
        "imports/retroarch/<slug:slug>/",
        views.ScrobbleRetroarchImportDetailView.as_view(),
        name="retroarch-import-detail",
    ),
    path(
        "charts/",
        views.ChartRecordView.as_view(),
        name="charts-home",
    ),
    path(
        "long-plays/",
        views.ScrobbleLongPlaysView.as_view(),
        name="long-plays",
    ),
    path("<slug:uuid>/start/", views.scrobble_start, name="start"),
    path("<slug:uuid>/finish/", views.scrobble_finish, name="finish"),
    path("<slug:uuid>/cancel/", views.scrobble_cancel, name="cancel"),
]

vrobbler/urls.py
from django.contrib import admin
from django.urls import include, path
from oauth2_provider import urls as oauth2_urls
from rest_framework import routers

import vrobbler.apps.scrobbles.views as scrobbles_views
from vrobbler.apps.boardgames import urls as boardgame_urls
from vrobbler.apps.books import urls as book_urls
from vrobbler.apps.books.api.views import AuthorViewSet, BookViewSet
from vrobbler.apps.bricksets import urls as bricksets_urls
from vrobbler.apps.lifeevents import urls as lifeevents_urls
from vrobbler.apps.locations import urls as locations_urls
from vrobbler.apps.moods import urls as moods_urls
from vrobbler.apps.music import urls as music_urls
from vrobbler.apps.music.api.views import (
    AlbumViewSet,
    ArtistViewSet,
    TrackViewSet,
)
from vrobbler.apps.podcasts import urls as podcast_urls
from vrobbler.apps.profiles.api.views import UserProfileViewSet, UserViewSet
from vrobbler.apps.scrobbles import urls as scrobble_urls
from vrobbler.apps.scrobbles.api.views import (
    AudioScrobblerTSVImportViewSet,
    KoReaderImportViewSet,
    LastFmImportViewSet,
    ScrobbleViewSet,
)
from vrobbler.apps.sports import urls as sports_urls
from vrobbler.apps.sports.api.views import (
    LeagueViewSet,
    PlayerViewSet,
    SeasonViewSet,
    SportEventViewSet,
    SportViewSet,
    TeamViewSet,
)
from vrobbler.apps.tasks import urls as tasks_urls
from vrobbler.apps.trails import urls as trails_urls
from vrobbler.apps.beers import urls as beers_urls
from vrobbler.apps.foods import urls as foods_urls
from vrobbler.apps.videogames import urls as videogame_urls
from vrobbler.apps.videos import urls as video_urls
from vrobbler.apps.videos.api.views import SeriesViewSet, VideoViewSet
from vrobbler.apps.webpages import urls as webpages_urls

router = routers.DefaultRouter()
router.register(r"scrobbles", ScrobbleViewSet)
router.register(r"lastfm-imports", LastFmImportViewSet)
router.register(r"tsv-imports", AudioScrobblerTSVImportViewSet)
router.register(r"koreader-imports", KoReaderImportViewSet)
router.register(r"artist", ArtistViewSet)
router.register(r"album", AlbumViewSet)
router.register(r"tracks", TrackViewSet)
router.register(r"series", SeriesViewSet)
router.register(r"videos", VideoViewSet)
router.register(r"authors", AuthorViewSet)
router.register(r"books", BookViewSet)
router.register(r"leagues", LeagueViewSet)
router.register(r"sports", SportViewSet)
router.register(r"seasons", SeasonViewSet)
router.register(r"players", PlayerViewSet)
router.register(r"sport-events", SportEventViewSet)
router.register(r"teams", TeamViewSet)
router.register(r"users", UserViewSet)
router.register(r"user_profiles", UserProfileViewSet)

urlpatterns = [
    path("api/v1/", include(router.urls)),
    path("api/v1/auth", include("rest_framework.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("o/", include(oauth2_urls)),
    path("", include(music_urls, namespace="music")),
    path("", include(book_urls, namespace="books")),
    path("", include(video_urls, namespace="videos")),
    path("", include(videogame_urls, namespace="videogames")),
    path("", include(boardgame_urls, namespace="boardgames")),
    path("", include(bricksets_urls, namespace="bricksets")),
    path("", include(sports_urls, namespace="sports")),
    path("", include(locations_urls, namespace="locations")),
    path("", include(trails_urls, namespace="trails")),
    path("", include(beers_urls, namespace="beers")),
    path("", include(foods_urls, namespace="foods")),
    path("", include(tasks_urls, namespace="tasks")),
    path("", include(webpages_urls, namespace="webpages")),
    path("", include(podcast_urls, namespace="podcasts")),
    path("", include(lifeevents_urls, namespace="life-events")),
    path("", include(moods_urls, namespace="moods")),
    path("", include(scrobble_urls, namespace="scrobbles")),
    path(
        "", scrobbles_views.RecentScrobbleList.as_view(), name="vrobbler-home"
    ),
]

vrobbler/apps/beers/models.py
from uuid import uuid4

from beers.untappd import get_beer_from_untappd_id, get_rating_from_soup
from django.apps import apps
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from scrobbles.dataclasses import BeerLogData
from scrobbles.mixins import ScrobblableConstants, ScrobblableMixin

BNULL = {"blank": True, "null": True}


class BeerStyle(TimeStampedModel):
    uuid = models.UUIDField(default=uuid4, editable=False, **BNULL)
    name = models.CharField(max_length=255)
    description = models.TextField(**BNULL)

    def __str__(self):
        return self.name


class BeerProducer(TimeStampedModel):
    uuid = models.UUIDField(default=uuid4, editable=False, **BNULL)
    name = models.CharField(max_length=255)
    description = models.TextField(**BNULL)
    location = models.CharField(max_length=255, **BNULL)
    beeradvocate_id = models.CharField(max_length=255, **BNULL)
    untappd_id = models.CharField(max_length=255, **BNULL)

    def find_or_create(cls, title: str) -> "BeerProducer":
        return cls.objects.filter(title=title).first()

    def __str__(self):
        return self.name


class Beer(ScrobblableMixin):
    description = models.TextField(**BNULL)
    ibu = models.SmallIntegerField(**BNULL)
    abv = models.FloatField(**BNULL)
    styles = models.ManyToManyField(BeerStyle, related_name="styles")
    non_alcoholic = models.BooleanField(default=False)
    beeradvocate_id = models.CharField(max_length=255, **BNULL)
    beeradvocate_score = models.SmallIntegerField(**BNULL)
    untappd_image = models.ImageField(upload_to="beers/untappd/", **BNULL)
    untappd_image_small = ImageSpecField(
        source="untappd_image",
        processors=[ResizeToFit(100, 100)],
        format="JPEG",
        options={"quality": 60},
    )
    untappd_image_medium = ImageSpecField(
        source="untappd_image",
        processors=[ResizeToFit(300, 300)],
        format="JPEG",
        options={"quality": 75},
    )
    untappd_id = models.CharField(max_length=255, **BNULL)
    untappd_rating = models.FloatField(**BNULL)
    producer = models.ForeignKey(
        BeerProducer, on_delete=models.DO_NOTHING, **BNULL
    )

    def get_absolute_url(self) -> str:
        return reverse("beers:beer_detail", kwargs={"slug": self.uuid})

    def __str__(self):
        return f"{self.title} by {self.producer}"

    @property
    def subtitle(self):
        return self.producer.name

    @property
    def strings(self) -> ScrobblableConstants:
        return ScrobblableConstants(verb="Drinking", tags="beer")

    @property
    def beeradvocate_link(self) -> str:
        link = ""
        if self.producer and self.beeradvocate_id:
            if self.beeradvocate_id:
                link = f"https://www.beeradvocate.com/beer/profile/{self.producer.beeradvocate_id}/{self.beeradvocate_id}/"
        return link

    @property
    def untappd_link(self) -> str:
        link = ""
        if self.untappd_id:
            link = f"https://www.untappd.com/beer/{self.untappd_id}/"
        return link

    @property
    def primary_image_url(self) -> str:
        url = ""
        if self.untappd_image:
            url = self.untappd_image.url
        return url

    @property
    def logdata_cls(self):
        return BeerLogData

    @classmethod
    def find_or_create(cls, untappd_id: str) -> "Beer":
        beer = cls.objects.filter(untappd_id=untappd_id).first()

        if not beer:
            beer_dict = get_beer_from_untappd_id(untappd_id)
            producer_dict = {}
            style_ids = []
            for key in list(beer_dict.keys()):
                if "producer__" in key:
                    pkey = key.replace("producer__", "")
                    producer_dict[pkey] = beer_dict.pop(key)
                if "styles" in key:
                    for style in beer_dict.pop("styles"):
                        style_inst, created = BeerStyle.objects.get_or_create(
                            name=style
                        )
                        style_ids.append(style_inst.id)

            producer, _created = BeerProducer.objects.get_or_create(
                **producer_dict
            )
            beer_dict["producer_id"] = producer.id
            beer = Beer.objects.create(**beer_dict)
            for style_id in style_ids:
                beer.styles.add(style_id)

        return beer

    def scrobbles(self, user_id):
        Scrobble = apps.get_model("scrobbles", "Scrobble")
        return Scrobble.objects.filter(user_id=user_id, beer=self).order_by(
            "-timestamp"
        )

vrobbler/apps/bricksets/models.py
from django.apps import apps
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from scrobbles.dataclasses import BrickSetLogData
from scrobbles.mixins import LongPlayScrobblableMixin

BNULL = {"blank": True, "null": True}


class BrickSet(LongPlayScrobblableMixin):
    """"""

    number = models.CharField(max_length=10, **BNULL)
    release_year = models.IntegerField(**BNULL)
    piece_count = models.IntegerField(**BNULL)
    brickset_rating = models.DecimalField(max_digits=3, decimal_places=1, **BNULL)
    lego_item_number = models.CharField(max_length=10, **BNULL)
    box_image = models.ImageField(upload_to="brickset/boxes/", **BNULL)
    box_image_small = ImageSpecField(
        source="box_image",
        processors=[ResizeToFit(100, 100)],
        format="JPEG",
        options={"quality": 60},
    )
    box_image_medium = ImageSpecField(
        source="box_image",
        processors=[ResizeToFit(300, 300)],
        format="JPEG",
        options={"quality": 75},
    )
    set_image = models.ImageField(upload_to="brickset/sets/", **BNULL)
    set_image_small = ImageSpecField(
        source="set_image",
        processors=[ResizeToFit(100, 100)],
        format="JPEG",
        options={"quality": 60},
    )
    set_image_medium = ImageSpecField(
        source="set_image",
        processors=[ResizeToFit(300, 300)],
        format="JPEG",
        options={"quality": 75},
    )

    def get_absolute_url(self):
        return reverse("bricksets:brickset_detail", kwargs={"slug": self.uuid})

    @property
    def logdata_cls(self):
        return BrickSetLogData

    @classmethod
    def find_or_create(cls, title: str) -> "BrickSet":
        return cls.objects.filter(title=title).first()

    @property
    def primary_image_url(self) -> str:
        if self.box_image:
            return self.box_image.url
        return ""

vrobbler/apps/lifeevents/models.py
from django.apps import apps
from django.db import models
from django.urls import reverse
from scrobbles.dataclasses import LifeEventLogData
from scrobbles.mixins import ScrobblableConstants, ScrobblableMixin

BNULL = {"blank": True, "null": True}


class LifeEvent(ScrobblableMixin):
    description = models.TextField(**BNULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "life-events:life-event_detail", kwargs={"slug": self.uuid}
        )

    @property
    def logdata_cls(self):
        return LifeEventLogData

    @property
    def strings(self) -> ScrobblableConstants:
        return ScrobblableConstants(verb="Experiencing", tags="camping")

    @classmethod
    def find_or_create(cls, title: str) -> "LifeEvent":
        return cls.objects.filter(title=title).first()

    def scrobbles(self, user_id):
        Scrobble = apps.get_model("scrobbles", "Scrobble")
        return Scrobble.objects.filter(
            user_id=user_id, life_event=self
        ).order_by("-timestamp")

vrobbler/apps/scrobbles/forms.py
from django import forms


class ExportScrobbleForm(forms.Form):
    """Provide options for downloading scrobbles"""

    EXPORT_TYPES = (
        ("as", "Audioscrobbler"),
        ("csv", "CSV"),
        ("html", "HTML"),
    )
    export_type = forms.ChoiceField(choices=EXPORT_TYPES)


class ScrobbleForm(forms.Form):
    item_id = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-dark w-100",
                "placeholder": "Scrobble something (ttIMDB, -v Video Game title, -b Book title, -s TheSportsDB ID)",
                "aria-label": "Scrobble something",
            }
        ),
    )

vrobbler/apps/webpages/forms.py
from django import forms
from django.urls import reverse_lazy

class WebPageReadForm(forms.Form):
    notes = forms.CharField(widget=forms.Textarea, required=False)
    success_url = reverse_lazy("vrobbler-home")

vrobbler/templates/base.html
{% load static %}
{% load humanize %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <title>{% block page_title %}Scrobble all the things{% endblock %} @ Vrobbler</title>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.10/clipboard.min.js"></script>
        <style type="text/css">
        dl {
            display: flex;
            flex-flow: column wrap;
            border: 1px solid #777;
        }
        dt {
            padding: 2px 4px;
            background: #000;
            color: #fff;
        }
        dd {
            margin: 0;
            padding: 4px;
            min-height: 3em;
            border-right: 1px solid #777;
        }
        .now-playing { margin-right:20px;}
        .now-playing p { margin:0; }
        .now-playing .right { float:right; margin-right:10px; }
        .latest-scrobble {
            width: 50%;
        }
        .now-playing img { height:75px; width: 75px; object-fit: cover; }

        .progress-bar {
            width: 100%;
            background-color: #e0e0e0;
            padding: 3px;
            border-radius: 3px;
            box-shadow: inset 0 1px 3px rgba(0, 0, 0, .2);
        }

        .progress-bar-fill {
            display: block;
            height: 22px;
            background-color: #659cef;
            border-radius: 3px;
            transition: width 500ms ease-in-out;
        }
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }
        body {
        font-size: .875rem;
        }

        .feather {
        width: 16px;
        height: 16px;
        vertical-align: text-bottom;
        }

        /*
        * Sidebar
        */

        .sidebar {
        position: fixed;
        top: 0;
        /* rtl:raw:
        right: 0;
        */
        bottom: 0;
        /* rtl:remove */
        left: 0;
        z-index: 100; /* Behind the navbar */
        padding: 48px 0 0; /* Height of navbar */
        box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        }

        @media (max-width: 767.98px) {
        .sidebar {
            top: 5rem;
        }
        }

        .sidebar-sticky {
        position: relative;
        top: 0;
        height: calc(100vh - 48px);
        padding-top: .5rem;
        overflow-x: hidden;
        overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }

        .sidebar .nav-link {
        font-weight: 500;
        color: #333;
        }

        .sidebar .nav-link .feather {
        margin-right: 4px;
        color: #727272;
        }

        .sidebar .nav-link.active {
        color: #2470dc;
        }

        .sidebar .nav-link:hover .feather,
        .sidebar .nav-link.active .feather {
        color: inherit;
        }

        .sidebar-heading {
        font-size: .75rem;
        text-transform: uppercase;
        }

        /*
        * Navbar
        */

        .navbar-brand {
        padding-top: .75rem;
        padding-bottom: .75rem;
        font-size: 1rem;
        background-color: rgba(0, 0, 0, .25);
        box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
        }

        .navbar .navbar-toggler {
        top: .25rem;
        right: 1rem;
        }

        .navbar .form-control {
        padding: .75rem 1rem;
        border-width: 0;
        border-radius: 0;
        }

        .form-control-dark {
        color: #fff;
        background-color: rgba(255, 255, 255, .1);
        border-color: rgba(255, 255, 255, .1);
        }

        .form-control-dark:focus {
        border-color: transparent;
        box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
        }
        #scrobble-form { width: 100% }
        </style>
        {% block head_extra %}{% endblock %}

        <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">
    </head>
    <body>
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Vrobbler</a>
            <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% if user.is_authenticated %}
            <form id="scrobble-form" action="{% url 'scrobbles:lookup-manual-scrobble' %}" method="post">
                {% csrf_token %}
                {{ imdb_form }}
            </form>
            {% endif %}
            <div class="navbar-nav">
                <div class="nav-item text-nowrap">
                    {% if user.is_authenticated %}
                    <a class="nav-link px-3" href="{% url "account_logout" %}">Sign out</a>
                    {% else %}
                    <a class="nav-link px-3" href="{% url "account_login" %}">Sign in</a>
                {% endif %}
                </div>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3">
                        {% if messages %}
                        <ul style="padding-right:10px;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        </ul>
                        {% endif %}
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/">
                                <span data-feather="music"></span>
                                Dashboard
                                </a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="/charts/">
                                <span data-feather="bar-chart"></span>
                                Charts
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="/locations/">
                                <span data-feather="map"></span>
                                Locations
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/long-plays/">
                                <span data-feather="playv"></span>
                                Long plays
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/moods/">
                                <span data-feather="smiley"></span>
                                Moods
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/books/">
                                <span data-feather="book"></span>
                                Books
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/video-games/">
                                <span data-feather="video"></span>
                                Video games
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/board-games/">
                                <span data-feather="board"></span>
                                Board games
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/trails/">
                                <span data-feather="trail"></span>
                                Trails
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/beers/">
                                <span data-feather="beer"></span>
                                Beers
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/imports/">
                                <span data-feather="log"></span>
                                Imports
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/admin/">
                                <span data-feather="key"></span>
                                Admin
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                        {% block extra_nav %}
                        {% endblock %}
                        <hr/>

                        {% if now_playing_list and user.is_authenticated %}
                        <ul>
                            <b>Now playing</b>
                            {% for scrobble in now_playing_list %}
                            <div class="now-playing">
                                {% if scrobble.media_obj.primary_image_url %}<div style="float:left;padding-right:10px;padding-bottom:10px;"><img src="{{scrobble.media_obj.primary_image_url}}" /></div>{% endif %}
                                <p><a href="{{scrobble.media_obj.get_absolute_url}}">{{scrobble.media_obj.title}}</a></p>
                                {% if scrobble.media_obj.subtitle %}<p><em><a href="{{scrobble.media_obj.subtitle.get_absolute_url}}">{{scrobble.media_obj.subtitle}}</a></em></p>{% endif %}
                                {% if scrobble.logdata %}{% if scrobble.logdata.description %}<p><em>{{scrobble.logdata.description}}</em></p>{% endif %}{% endif %}
                                <p><small>{{scrobble.timestamp|naturaltime}} from {{scrobble.source}}</small></p>
                                <div class="progress-bar" style="margin-right:5px;">
                                    <span class="progress-bar-fill" style="width: {{scrobble.percent_played}}%;"></span>
                                </div>
                                <p class="action-buttons">
                                    <a href="{% url "scrobbles:cancel" scrobble.uuid %}">Cancel</a>
                                    <a class="right" href="{% url "scrobbles:finish" scrobble.uuid %}">Finish</a>
                                </p>
                                {% if not forloop.last %}<hr/>{% endif %}
                            </div>
                            {% endfor %}
                        </ul>
                        {% if now_playing_list|length > 1 %}<hr/>{% endif %}
                        {% endif %}

                        {% if active_imports %}
                        {% for import in active_imports %}
                        <ul style="padding-right:10px;">
                            <li>Import in progress ({{import.processing_started|naturaltime}})</li>
                        </ul>
                        {% endfor %}
                        {% endif %}

                    </div>
                </nav>

                {% block content %}
                {% endblock %}
            </div>
        </div>

        {% block extra_js %}{% endblock %}
    </body>
</html>

vrobbler/templates/base_detail.html
{% extends "base.html" %}

{% block content %}
<main class="col-md-4 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{% block title %}{% endblock %} </h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
        </div>
    </div>

    <div class="container">
        {% block details %}{% endblock %}
    </div>
</main>
{% endblock %}