vrobbler/apps/beers/urls.py
from django.urls import path
from beers import views

app_name = "beers"


urlpatterns = [
    path("beers/", views.BeerListView.as_view(), name="beer_list"),
    path(
        "beers/<slug:slug>/",
        views.BeerDetailView.as_view(),
        name="beer_detail",
    ),
]

vrobbler/apps/books/urls.py
from django.urls import path
from books import views

app_name = "books"


urlpatterns = [
    path("books/", views.BookListView.as_view(), name="book_list"),
    path(
        "books/<slug:slug>/",
        views.BookDetailView.as_view(),
        name="book_detail",
    ),
    path(
        "authors/<slug:slug>/",
        views.AuthorDetailView.as_view(),
        name="author_detail",
    ),
]

vrobbler/apps/foods/urls.py
from django.urls import path
from foods import views

app_name = "foods"


urlpatterns = [
    path("foods/", views.FoodListView.as_view(), name="food_list"),
    path(
        "foods/<slug:slug>/",
        views.FoodDetailView.as_view(),
        name="food_detail",
    ),
]

vrobbler/apps/scrobbles/urls.py
from django.urls import path
from scrobbles import views
from tasks.webhooks import todoist_webhook

app_name = "scrobbles"

urlpatterns = [
    path("status/", views.ScrobbleStatusView.as_view(), name="status"),
    path(
        "manual/lookup/",
        views.ManualScrobbleView.as_view(),
        name="lookup-manual-scrobble",
    ),
    path(
        "long-play-finish/<slug:uuid>/",
        views.scrobble_longplay_finish,
        name="longplay-finish",
    ),
    path(
        "upload/audioscrobbler/",
        views.AudioScrobblerImportCreateView.as_view(),
        name="audioscrobbler-file-upload",
    ),
    path(
        "upload/koreader/",
        views.KoReaderImportCreateView.as_view(),
        name="koreader-file-upload",
    ),
    path(
        "lastfm-import/",
        views.lastfm_import,
        name="lastfm-import",
    ),
    path(
        "webhook/web-scrobbler/",
        views.web_scrobbler_webhook,
        name="web-scrobbler-webhook",
    ),
    path(
        "webhook/gps/",
        views.gps_webhook,
        name="gps-webhook",
    ),
    path(
        "webhook/jellyfin/",
        views.jellyfin_webhook,
        name="jellyfin-webhook",
    ),
    path(
        "webhook/mopidy/",
        views.mopidy_webhook,
        name="mopidy-webhook",
    ),
    path("webhook/todoist/", todoist_webhook, name="todoist-webhook"),
    path("export/", views.export, name="export"),
    path(
        "imports/",
        views.ScrobbleImportListView.as_view(),
        name="import-detail",
    ),
    path(
        "imports/tsv/<slug:slug>/",
        views.ScrobbleTSVImportDetailView.as_view(),
        name="tsv-import-detail",
    ),
    path(
        "imports/lastfm/<slug:slug>/",
        views.ScrobbleLastFMImportDetailView.as_view(),
        name="lastfm-import-detail",
    ),
    path(
        "imports/koreader/<slug:slug>/",
        views.ScrobbleKoReaderImportDetailView.as_view(),
        name="koreader-import-detail",
    ),
    path(
        "imports/retroarch/<slug:slug>/",
        views.ScrobbleRetroarchImportDetailView.as_view(),
        name="retroarch-import-detail",
    ),
    path(
        "charts/",
        views.ChartRecordView.as_view(),
        name="charts-home",
    ),
    path(
        "long-plays/",
        views.ScrobbleLongPlaysView.as_view(),
        name="long-plays",
    ),
    path("<slug:uuid>/start/", views.scrobble_start, name="start"),
    path("<slug:uuid>/finish/", views.scrobble_finish, name="finish"),
    path("<slug:uuid>/cancel/", views.scrobble_cancel, name="cancel"),
]

vrobbler/urls.py
from django.contrib import admin
from django.urls import include, path
from oauth2_provider import urls as oauth2_urls
from rest_framework import routers

import vrobbler.apps.scrobbles.views as scrobbles_views
from vrobbler.apps.boardgames import urls as boardgame_urls
from vrobbler.apps.books import urls as book_urls
from vrobbler.apps.books.api.views import AuthorViewSet, BookViewSet
from vrobbler.apps.bricksets import urls as bricksets_urls
from vrobbler.apps.lifeevents import urls as lifeevents_urls
from vrobbler.apps.locations import urls as locations_urls
from vrobbler.apps.moods import urls as moods_urls
from vrobbler.apps.music import urls as music_urls
from vrobbler.apps.music.api.views import (
    AlbumViewSet,
    ArtistViewSet,
    TrackViewSet,
)
from vrobbler.apps.podcasts import urls as podcast_urls
from vrobbler.apps.profiles.api.views import UserProfileViewSet, UserViewSet
from vrobbler.apps.scrobbles import urls as scrobble_urls
from vrobbler.apps.scrobbles.api.views import (
    AudioScrobblerTSVImportViewSet,
    KoReaderImportViewSet,
    LastFmImportViewSet,
    ScrobbleViewSet,
)
from vrobbler.apps.sports import urls as sports_urls
from vrobbler.apps.sports.api.views import (
    LeagueViewSet,
    PlayerViewSet,
    SeasonViewSet,
    SportEventViewSet,
    SportViewSet,
    TeamViewSet,
)
from vrobbler.apps.tasks import urls as tasks_urls
from vrobbler.apps.trails import urls as trails_urls
from vrobbler.apps.beers import urls as beers_urls
from vrobbler.apps.foods import urls as foods_urls
from vrobbler.apps.videogames import urls as videogame_urls
from vrobbler.apps.videos import urls as video_urls
from vrobbler.apps.videos.api.views import SeriesViewSet, VideoViewSet
from vrobbler.apps.webpages import urls as webpages_urls

router = routers.DefaultRouter()
router.register(r"scrobbles", ScrobbleViewSet)
router.register(r"lastfm-imports", LastFmImportViewSet)
router.register(r"tsv-imports", AudioScrobblerTSVImportViewSet)
router.register(r"koreader-imports", KoReaderImportViewSet)
router.register(r"artist", ArtistViewSet)
router.register(r"album", AlbumViewSet)
router.register(r"tracks", TrackViewSet)
router.register(r"series", SeriesViewSet)
router.register(r"videos", VideoViewSet)
router.register(r"authors", AuthorViewSet)
router.register(r"books", BookViewSet)
router.register(r"leagues", LeagueViewSet)
router.register(r"sports", SportViewSet)
router.register(r"seasons", SeasonViewSet)
router.register(r"players", PlayerViewSet)
router.register(r"sport-events", SportEventViewSet)
router.register(r"teams", TeamViewSet)
router.register(r"users", UserViewSet)
router.register(r"user_profiles", UserProfileViewSet)

urlpatterns = [
    path("api/v1/", include(router.urls)),
    path("api/v1/auth", include("rest_framework.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("o/", include(oauth2_urls)),
    path("", include(music_urls, namespace="music")),
    path("", include(book_urls, namespace="books")),
    path("", include(video_urls, namespace="videos")),
    path("", include(videogame_urls, namespace="videogames")),
    path("", include(boardgame_urls, namespace="boardgames")),
    path("", include(bricksets_urls, namespace="bricksets")),
    path("", include(sports_urls, namespace="sports")),
    path("", include(locations_urls, namespace="locations")),
    path("", include(trails_urls, namespace="trails")),
    path("", include(beers_urls, namespace="beers")),
    path("", include(foods_urls, namespace="foods")),
    path("", include(tasks_urls, namespace="tasks")),
    path("", include(webpages_urls, namespace="webpages")),
    path("", include(podcast_urls, namespace="podcasts")),
    path("", include(lifeevents_urls, namespace="life-events")),
    path("", include(moods_urls, namespace="moods")),
    path("", include(scrobble_urls, namespace="scrobbles")),
    path(
        "", scrobbles_views.RecentScrobbleList.as_view(), name="vrobbler-home"
    ),
]

scrobbles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_extensions.db.models import TimeStampedModel

from videos.models import Video

User = get_user_model()
BNULL = {"blank": True, "null": True}


class Scrobble(TimeStampedModel):
    video = models.ForeignKey(Video, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.DO_NOTHING
    )
    timestamp = models.DateTimeField(**BNULL)
    playback_position_ticks = models.PositiveIntegerField(**BNULL)
    playback_position = models.CharField(max_length=8, **BNULL)
    is_paused = models.BooleanField(default=False)
    played_to_completion = models.BooleanField(default=False)
    source = models.CharField(max_length=255, **BNULL)
    source_id = models.TextField(**BNULL)
    in_progress = models.BooleanField(default=True)
    scrobble_log = models.TextField(**BNULL)

    @property
    def percent_played(self) -> int:
        return int(
            (self.playback_position_ticks / self.video.run_time_ticks) * 100
        )

    def __str__(self):
        return f"Scrobble of {self.video} {self.timestamp.year}-{self.timestamp.month}"

videos/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.utils.translation import gettext_lazy as _

BNULL = {"blank": True, "null": True}


class Series(TimeStampedModel):
    name = models.CharField(max_length=255)
    overview = models.TextField(**BNULL)
    tagline = models.TextField(**BNULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "series"


class Video(TimeStampedModel):
    class VideoType(models.TextChoices):
        UNKNOWN = 'U', _('Unknown')
        TV_EPISODE = 'E', _('TV Episode')
        MOVIE = 'M', _('Movie')

    # General fields
    video_type = models.CharField(
        max_length=1,
        choices=VideoType.choices,
        default=VideoType.UNKNOWN,
    )
    title = models.CharField(max_length=255, **BNULL)
    overview = models.TextField(**BNULL)
    tagline = models.TextField(**BNULL)
    run_time = models.CharField(max_length=8, **BNULL)
    run_time_ticks = models.BigIntegerField(**BNULL)
    year = models.IntegerField()

    # TV show specific fields
    tv_series = models.ForeignKey(Series, on_delete=models.DO_NOTHING, **BNULL)
    season_number = models.IntegerField(**BNULL)
    episode_number = models.IntegerField(**BNULL)
    tvdb_id = models.CharField(max_length=20, **BNULL)
    imdb_id = models.CharField(max_length=20, **BNULL)
    tvrage_id = models.CharField(max_length=20, **BNULL)

    # Metadata fields from TMDB

    def __str__(self):
        if self.video_type == self.VideoType.TV_EPISODE:
            return f"{self.tv_series} - Season {self.season_number}, Episode {self.episode_number}"
        return self.title

vrobbler/apps/beers/models.py
from uuid import uuid4

from beers.untappd import get_beer_from_untappd_id, get_rating_from_soup
from django.apps import apps
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from scrobbles.dataclasses import BeerLogData
from scrobbles.mixins import ScrobblableConstants, ScrobblableMixin

BNULL = {"blank": True, "null": True}


class BeerStyle(TimeStampedModel):
    uuid = models.UUIDField(default=uuid4, editable=False, **BNULL)
    name = models.CharField(max_length=255)
    description = models.TextField(**BNULL)

    def __str__(self):
        return self.name


class BeerProducer(TimeStampedModel):
    uuid = models.UUIDField(default=uuid4, editable=False, **BNULL)
    name = models.CharField(max_length=255)
    description = models.TextField(**BNULL)
    location = models.CharField(max_length=255, **BNULL)
    beeradvocate_id = models.CharField(max_length=255, **BNULL)
    untappd_id = models.CharField(max_length=255, **BNULL)

    def find_or_create(cls, title: str) -> "BeerProducer":
        return cls.objects.filter(title=title).first()

    def __str__(self):
        return self.name


class Beer(ScrobblableMixin):
    description = models.TextField(**BNULL)
    ibu = models.SmallIntegerField(**BNULL)
    abv = models.FloatField(**BNULL)
    styles = models.ManyToManyField(BeerStyle, related_name="styles")
    non_alcoholic = models.BooleanField(default=False)
    beeradvocate_id = models.CharField(max_length=255, **BNULL)
    beeradvocate_score = models.SmallIntegerField(**BNULL)
    untappd_image = models.ImageField(upload_to="beers/untappd/", **BNULL)
    untappd_image_small = ImageSpecField(
        source="untappd_image",
        processors=[ResizeToFit(100, 100)],
        format="JPEG",
        options={"quality": 60},
    )
    untappd_image_medium = ImageSpecField(
        source="untappd_image",
        processors=[ResizeToFit(300, 300)],
        format="JPEG",
        options={"quality": 75},
    )
    untappd_id = models.CharField(max_length=255, **BNULL)
    untappd_rating = models.FloatField(**BNULL)
    producer = models.ForeignKey(
        BeerProducer, on_delete=models.DO_NOTHING, **BNULL
    )

    def get_absolute_url(self) -> str:
        return reverse("beers:beer_detail", kwargs={"slug": self.uuid})

    def __str__(self):
        return f"{self.title} by {self.producer}"

    @property
    def subtitle(self):
        return self.producer.name

    @property
    def strings(self) -> ScrobblableConstants:
        return ScrobblableConstants(verb="Drinking", tags="beer")

    @property
    def beeradvocate_link(self) -> str:
        link = ""
        if self.producer and self.beeradvocate_id:
            if self.beeradvocate_id:
                link = f"https://www.beeradvocate.com/beer/profile/{self.producer.beeradvocate_id}/{self.beeradvocate_id}/"
        return link

    @property
    def untappd_link(self) -> str:
        link = ""
        if self.untappd_id:
            link = f"https://www.untappd.com/beer/{self.untappd_id}/"
        return link

    @property
    def primary_image_url(self) -> str:
        url = ""
        if self.untappd_image:
            url = self.untappd_image.url
        return url

    @property
    def logdata_cls(self):
        return BeerLogData

    @classmethod
    def find_or_create(cls, untappd_id: str) -> "Beer":
        beer = cls.objects.filter(untappd_id=untappd_id).first()

        if not beer:
            beer_dict = get_beer_from_untappd_id(untappd_id)
            producer_dict = {}
            style_ids = []
            for key in list(beer_dict.keys()):
                if "producer__" in key:
                    pkey = key.replace("producer__", "")
                    producer_dict[pkey] = beer_dict.pop(key)
                if "styles" in key:
                    for style in beer_dict.pop("styles"):
                        style_inst, created = BeerStyle.objects.get_or_create(
                            name=style
                        )
                        style_ids.append(style_inst.id)

            producer, _created = BeerProducer.objects.get_or_create(
                **producer_dict
            )
            beer_dict["producer_id"] = producer.id
            beer = Beer.objects.create(**beer_dict)
            for style_id in style_ids:
                beer.styles.add(style_id)

        return beer

    def scrobbles(self, user_id):
        Scrobble = apps.get_model("scrobbles", "Scrobble")
        return Scrobble.objects.filter(user_id=user_id, beer=self).order_by(
            "-timestamp"
        )

vrobbler/apps/lifeevents/models.py
from django.apps import apps
from django.db import models
from django.urls import reverse
from scrobbles.dataclasses import LifeEventLogData
from scrobbles.mixins import ScrobblableConstants, ScrobblableMixin

BNULL = {"blank": True, "null": True}


class LifeEvent(ScrobblableMixin):
    description = models.TextField(**BNULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "life-events:life-event_detail", kwargs={"slug": self.uuid}
        )

    @property
    def logdata_cls(self):
        return LifeEventLogData

    @property
    def strings(self) -> ScrobblableConstants:
        return ScrobblableConstants(verb="Experiencing", tags="camping")

    @classmethod
    def find_or_create(cls, title: str) -> "LifeEvent":
        return cls.objects.filter(title=title).first()

    def scrobbles(self, user_id):
        Scrobble = apps.get_model("scrobbles", "Scrobble")
        return Scrobble.objects.filter(
            user_id=user_id, life_event=self
        ).order_by("-timestamp")

vrobbler/apps/scrobbles/forms.py
from django import forms


class ExportScrobbleForm(forms.Form):
    """Provide options for downloading scrobbles"""

    EXPORT_TYPES = (
        ("as", "Audioscrobbler"),
        ("csv", "CSV"),
        ("html", "HTML"),
    )
    export_type = forms.ChoiceField(choices=EXPORT_TYPES)


class ScrobbleForm(forms.Form):
    item_id = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-dark w-100",
                "placeholder": "Scrobble something (ttIMDB, -v Video Game title, -b Book title, -s TheSportsDB ID)",
                "aria-label": "Scrobble something",
            }
        ),
    )

vrobbler/templates/videos/movie_list.html
{% extends "base.html" %}

{% block content %}
<main class="col-md-4 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Movies</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
        </button>
        </div>
    </div>

    <div class="container">

    <ul>
        {% for movie in object_list %}
        <li>{{movie}}</li>
        {% endfor %}
    </ul>
    </div>
</main>
{% endblock %}

vrobbler/templates/videos/series_detail.html
{% extends "base_list.html" %}
{% load static %}

{% block title %}{{object.name}}{% if object.tv_series %} - {{object.tv_series}}{% endif %}{% endblock %}

{% block head_extra %}
<style>
.cover   {float:left; width:412px; margin-right:10px; padding-bottom:15px;}
.summary {float:left; width:600px; margin-left:10px;}
.header  {padding-bottom:15px;}
.image-wrapper { contain: content; }
.caption {
     position: fixed;
     top: 15px;
     left: 30px;
     padding: 5px;
     font-size: 110%;
     font-weight: bold;
     color:white;
     background:rgba(0,0,0,0.4);
}
</style>
{% endblock %}

{% block lists %}

<div class="row header">
    <div class="cover image-wrapper">
        {% if object.imdb_rating %}<div class="caption">{{object.imdb_rating}}</div>{% endif %}
        <img src="{% if object.cover_image %}{{object.cover_image.url}}{% else %}{% static 'images/no-video-cover.jpg' %}{% endif %}" width="400px" />
        {% if next_episode_id %}
        <form id="scrobble-form" action="{% url 'scrobbles:lookup-manual-scrobble' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" id="id_item_id" value="-i {{next_episode_id}}">
            <button type="submit" class="btn btn-primary">Start next episode</button>
        </form>
        {% endif %}
    </div>
    <div class="summary">
        {% if object.plot%}<p>{{object.plot|safe|linebreaks|truncatewords:160}}</p>{% endif %}
        <hr />
        <p style="float:right;">
            <a href="{{object.imdb_link}}"><img src="{% static "images/imdb_logo.png" %}" width=35></a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md">
        <h3>Last scrobbles</h3>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Title</th>
                        <th scope="col">Season</th>
                        <th scope="col">Episode</th>
                    </tr>
                </thead>
                <tbody>
                    {% for scrobble in scrobbles %}
                    <tr>
                        <td>{{scrobble.timestamp}}</td>
                        <td><a href="{{scrobble.media_obj.get_absolute_url}}">{{scrobble.media_obj.title}}</a></td>
                        <td>{{scrobble.media_obj.season_number}}</td>
                        <td>{{scrobble.media_obj.episode_number}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

vrobbler/templates/videos/series_list.html
{% extends "base_list.html" %}

{% block lists %}
<div class="row">
    <div class="col-md">
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Series</th>
                        <th scope="col">Episode</th>
                        <th scope="col">Scrobbles</th>
                        <th scope="col">All time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in object_list %}
                    {% for video in obj.video_set.all %}
                    <tr>
                        <td><a href="{{video.get_absolute_url}}">{{video}}</a></td>
                        <td><a href="{{obj.get_absolute_url}}">{{obj}}</a></td>
                        <td>{{video.scrobble_set.count}}</td>
                        <td></td>
                    </tr>
                    {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

vrobbler/templates/videos/video_detail.html
{% extends "base_list.html" %}
{% load static %}

{% block title %}{{object.title}}{% endblock %}

{% block head_extra %}
<style>
.cover   {float:left; width:412px; margin-right:10px; padding-bottom:15px;}
.summary {float:left; width:600px; margin-left:10px;}
.header  {padding-bottom:15px;}
.image-wrapper { contain: content; }
.caption {
     position: fixed;
     top: 15px;
     left: 30px;
     padding: 5px;
     font-size: 110%;
     font-weight: bold;
     color:white;
     background:rgba(0,0,0,0.4);
}
.caption-footer {
     position: fixed;
     bottom: 30px;
     left: 30px;
     padding: 5px;
     font-size: 110%;
     font-weight: bold;
     color:white;
     background:rgba(0,0,0,0.4);
}
dl {
    display: flex;
    flex-flow: row wrap;
    padding-right:20px;
    border:none;
}
dt {
    flex-basis: 20%;
    padding: 5px;
    background: #3cf;
    text-align: right;
    color: #fff;
}
dd {
    flex-basis: 70%;
    flex-grow: 1;
    margin: 0;
    padding: 5px;
    border:none;
}
</style>
{% endblock %}

{% block lists %}

<div class="row header">
    <div class="cover image-wrapper">
        {% if object.imdb_rating %}<div class="caption">{{object.imdb_rating}}</div>{% endif %}
        <img src="{% if object.cover_image %}{{object.cover_image.url}}{% else %}{% static 'images/no-video-cover.jpg' %}{% endif %}" width="400px" />
        <div class="caption-footer">{{object.year}}{% if object.tv_series %} | <b>S</b>{{object.season_number}} <b>E</b>{{object.episode_number}}{% endif %}</div>
    </div>
    <div class="summary">
    {% if object.tv_series %}<h4><a href="{{object.tv_series.get_absolute_url}}">{{object.tv_series}}</a> - S{{object.season_number}}E{{object.episode_number}}</h4>{% endif %}
        {% if object.overview %}<p><em>{{object.overview}}</em></p>{% endif %}
        {% if object.plot%}<p>{{object.plot|safe|linebreaks|truncatewords:160}}</p>{% endif %}
        <hr />
        <p style="float:right;">
            <a href="{{object.imdb_link}}"><img src="{% static "images/imdb_logo.png" %}" width=35></a>
        </p>

    </div>
    <div class="deets">
    </div>
</div>
<div class="row">
    <div class="col-md">
        <h3>Last scrobbles</h3>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for scrobble in object.scrobble_set.all %}
                    <tr>
                        <td>{{scrobble.timestamp}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}